<?php

/**
 * 4 BHK builder-floor areas expanded by SeoLandingFourBhkAreaExpander.
 * DLF Phase 1 is hand-crafted in seo_landing_4bhk.php and skipped if duplicated.
 */
return [
    'DLF Phase 2',
    'DLF Phase 3',
    'DLF Phase 4',
    'DLF Phase 5',
    'DLF Alameda',
    'DLF Gardencity',
    'Sushant Lok 1',
    'Sushant Lok 2',
    'Sushant Lok 3',
    'South City 1',
    'South City 2',
    'Palam Vihar',
    'New Palam Vihar',
    'Udyog Vihar Phase 1',
    'Udyog Vihar Phase 2',
    'Udyog Vihar Phase 3',
    'Udyog Vihar Phase 4',
    'Udyog Vihar Phase 5',
    'Cyber City',
    'Cyber Hub',
    'MG Road',
    'Golf Course Road',
    'Golf Course Extension Road',
    'Sohna Road',
    'Southern Peripheral Road (SPR)',
    'Dwarka Expressway',
    'Nirvana Country',
    'Malibu Town',
    'Mayfield Garden',
    'Rosewood City',
    'Greenwood City',
    'Ardee City',
    'Sun City',
    'Vatika City',
    'Central Park',
    'Vipul World',
    'Ansal Esencia',
    'Emerald Hills',
    'Orchid Island',
    'Hamilton Court',
    'Richmond Park',
    'Heritage City',
    'Saraswati Vihar',
    'Ashok Vihar',
    'Rajendra Park',
    'New Colony',
    'Civil Lines',
    'Jacobpura',
    'Patel Nagar',
    'Prem Nagar',
    'Krishna Colony',
    'Jyoti Park',
    'Laxman Vihar',
    'Shivpuri',
    'Sector 1',
    'Sector 2',
    'Sector 3',
    'Sector 4',
    'Sector 5',
    'Sector 6',
    'Sector 7',
    'Sector 9',
    'Sector 9A',
    'Sector 10',
    'Sector 10A',
    'Sector 12',
    'Sector 12A',
    'Sector 13',
    'Sector 14',
    'Sector 15 Part 1',
    'Sector 15 Part 2',
    'Sector 17',
    'Sector 21',
    'Sector 22',
    'Sector 23',
    'Sector 23A',
    'Sector 24',
    'Sector 25',
    'Sector 26',
    'Sector 27',
    'Sector 28',
    'Sector 29',
    'Sector 30',
    'Sector 31',
    'Sector 32',
    'Sector 33',
    'Sector 34',
    'Sector 37',
    'Sector 37C',
    'Sector 37D',
    'Sector 38',
    'Sector 39',
    'Sector 40',
    'Sector 41',
    'Sector 42',
    'Sector 43',
    'Sector 44',
    'Sector 45',
    'Sector 46',
    'Sector 47',
    'Sector 48',
    'Sector 49',
    'Sector 50',
    'Sector 51',
    'Sector 52',
    'Sector 52A',
    'Sector 53',
    'Sector 54',
    'Sector 55',
    'Sector 56',
    'Sector 57',
    'Sector 58',
    'Sector 59',
    'Sector 60',
    'Sector 61',
    'Sector 62',
    'Sector 63',
    'Sector 63A',
    'Sector 64',
    'Sector 65',
    'Sector 66',
    'Sector 67',
    'Sector 67A',
    'Sector 68',
    'Sector 69',
    'Sector 70',
    'Sector 70A',
    'Sector 71',
    'Sector 72',
    'Sector 73',
    'Sector 74',
    'Sector 74A',
    'Sector 75',
    'Sector 76',
    'Sector 77',
    'Sector 78',
    'Sector 79',
    'Sector 80',
    'Sector 81',
    'Sector 82',
    'Sector 82A',
    'Sector 83',
    'Sector 84',
    'Sector 85',
    'Sector 86',
    'Sector 87',
    'Sector 88',
    'Sector 88A',
    'Sector 89',
    'Sector 90',
    'Sector 91',
    'Sector 92',
    'Sector 93',
    'Sector 93A',
    'Sector 95',
    'Sector 95A',
    'Sector 99',
    'Sector 99A',
    'Sector 102',
    'Sector 103',
    'Sector 104',
    'Sector 105',
    'Sector 106',
    'Sector 107',
    'Sector 108',
    'Sector 109',
    'Sector 110',
    'Sector 110A',
    'Sector 111',
    'Sector 112',
    'Sector 113',
    'Sector 114',
    'Sector 115',
    'Manesar',
    'IMT Manesar',
    'Kadarpur',
    'Wazirabad',
    'Sikanderpur',
    'Nathupur',
    'Chakkarpur',
    'Badshahpur',
    'Bhondsi',
    'Ghata',
    'Gwal Pahari',
    'Begumpur Khatola',
    'Fazilpur Jharsa',
    'Jharsa',
    'Islampur',
    'Dundahera',
    'Carterpuri',
    'Basai',
    'Tikri',
    'Hayatpur',
    'Kherki Daula',
    'Farrukhnagar',
    'Pataudi',
    'Sohna',
];
